substitutions:
  # Default name
  name: "desk-lamp"
  # Default friendly name
  friendly_name: "Desk Lamp"
  # Define logging level: NONE, ERROR, WARN, INFO (Default), DEBUG, VERBOSE, VERY_VERBOSE
  log_level: "INFO"
  # Enables faster network connections, with last connected SSID being connected to and no full scan for SSID being undertaken
  wifi_fast_connect: "false"
  # Set timezone of the smart plug. Useful if the plug is in a location different to the HA server. Can be entered in unix Country/Area format (i.e. "Australia/Sydney")
  timezone: ""
  # Set the duration between the sntp service polling ntp.org servers for an update
  sntp_update_interval: 6h
  # Network time servers for your region, enter from lowest to highest priority. To use local servers update as per zones or countries at: https://www.ntppool.org/zone/@
  sntp_server_1: "0.pool.ntp.org"
  sntp_server_2: "1.pool.ntp.org"
  sntp_server_3: "2.pool.ntp.org"
  # Restore the light state upon reboot to state:
  restore_mode: RESTORE_DEFAULT_OFF
  # Project Name
  project_name: "kovapatrik.XiaomiDeskLamp1S"
  # Projection version denotes the release version of the yaml file, allowing checking of deployed vs latest version
  project_version: "1.0.3"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: ${project_name}
    version: ${project_version}

dashboard_import:
  package_import_url: github://kovapatrik/xiaomi-desk-lamp-1s-esphome/config.yaml

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
    advanced:
      ignore_efuse_mac_crc: true
      # See https://github.com/esphome/issues/issues/6333
      ignore_efuse_custom_mac: true

logger:
  level: ${log_level}
  baud_rate: 0

api:

ota:
  - platform: esphome

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap: {}
  fast_connect: "${wifi_fast_connect}"

captive_portal:

web_server:
  port: 80

time:
  - platform: sntp
    id: sntp_time
    # Define the timezone of the device
    timezone: "${timezone}"
    # Change sync interval from default 5min to 6 hours (or as set in substitutions)
    update_interval: ${sntp_update_interval}
    # Set specific sntp servers to use
    servers:
      - "${sntp_server_1}"
      - "${sntp_server_2}"
      - "${sntp_server_3}"

# Text sensors with general information
text_sensor:
  - platform: version
    name: "Version"
    icon: mdi:cube-outline

  - platform: wifi_info
    ip_address:
      name: "IP Address"
      icon: mdi:lan

button:
  - platform: factory_reset
    name: "Factory Reset"
    id: Reset
    entity_category: config

sensor:
  # Uptime sensor
  - platform: uptime
    name: "Uptime"
    update_interval: 60s
    icon: mdi:clock-outline

  # WiFi Signal sensor
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    icon: mdi:wifi

  # Knob
  - platform: rotary_encoder
    id: rotation
    pin_a: GPIO27
    pin_b: GPIO26
    resolution: 2
    on_value:
      then:
        - if:
            condition:
              # Check if Knob is pressed while rotating
              lambda: "return id(knob).state;"
            then:
              # If Knob is pressed, change CW/WW
              - lambda: |-
                  auto min_temp = id(light1).get_traits().get_min_mireds();
                  auto max_temp = id(light1).get_traits().get_max_mireds();
                  auto cur_temp = id(light1).current_values.get_color_temperature();
                  auto new_temp = max(min_temp, min(max_temp, cur_temp + (x*10)));
                  auto call = id(light1).turn_on();
                  call.set_color_temperature(new_temp);
                  call.perform();
            else:
              # If Button is not pressed, change brightness
              - light.dim_relative:
                  id: light1
                  brightness_limits:
                    min_brightness: 2%
                  relative_brightness: !lambda |-
                    return x / 25.0;
        # Reset Rotation to 0
        - sensor.rotary_encoder.set_value:
            id: rotation
            value: 0

binary_sensor:
  # Knob push-button
  - platform: gpio
    id: knob
    pin:
      number: GPIO33
      inverted: True
      mode: INPUT_PULLDOWN
    on_click:
      then:
        - light.toggle:
            id: light1
            transition_length: 0.2s
    filters:
      - delayed_off: 5ms

  # Reset button on the bottom of the lamp. Pushing it for 4s will cause a pulse effect on the lamp and it will factory reset it.
  - platform: gpio
    id: reset_button
    pin:
      number: GPIO16
      inverted: True
    on_multi_click:
      - timing:
          - ON for at least 4s
        then:
          - repeat:
              count: 3
              then:
                - light.turn_on:
                    id: light1
                    transition_length: 1s
                - delay: 1s
                - light.turn_off:
                    id: light1
                    transition_length: 1s
                - delay: 1s
          - button.press: "Reset"

output:
  - platform: ledc
    pin: GPIO2
    id: output_cw
    power_supply: power
    frequency: 40000Hz

  - platform: ledc
    pin: GPIO4
    id: output_ww
    power_supply: power
    frequency: 40000Hz

power_supply:
  - id: power
    pin: GPIO12
    enable_time: 0s
    keep_on_time: 0s

light:
  - platform: cwww
    id: light1
    name: "Light"
    default_transition_length: 0s
    constant_brightness: true
    cold_white: output_cw
    warm_white: output_ww
    cold_white_color_temperature: 4800 K
    # 2500k is the original value of the lamp. To correct binning for 2700k to look more like 2700k use 2650k instead
    warm_white_color_temperature: 2650 K
    restore_mode: ${restore_mode}
    gamma_correct: 0
